/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.midas.classify.gui;

import java.awt.BorderLayout;
import java.awt.Component;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author eduarc
 */
public class FromFilePanel extends javax.swing.JPanel {

  /**
   * Creates new form FromFilePanel
   * @param cPanel
   */
  public FromFilePanel(ClassificationPanel cPanel) {
    initComponents();
    
    this.cPanel = cPanel;
    
    fileChooser = new JFileChooser();
    fileChooser.setMultiSelectionEnabled(false);
    fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    fileChooser.setAcceptAllFileFilterUsed(false);
    fileChooser.addChoosableFileFilter(new FileFilter() {
      @Override
      public boolean accept(File f) {
        return f.isDirectory() || f.getName().toLowerCase().endsWith(".arff");
      }
      @Override
      public String getDescription() {
        return "ARFF Transactional File";
      }
    });
    
    dialog = new PopupDialog(cPanel) {

      @Override
      public int onCancel() {
        return DISPOSE;
      }

      @Override
      public int onOk() {
        
        if (input == null) {
          JOptionPane.showMessageDialog(this, "No input file", "Info", JOptionPane.INFORMATION_MESSAGE);
          return PopupDialog.VISIBLE;
        }
        
        return DISPOSE;
      }
    };
    dialog.setTitle("From File");
    dialog.setViewportView(this);
    
    input = output = null;
  }

  public int showDialog(Component parent) {
    return dialog.showDialog(parent);
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    bInput = new javax.swing.JButton();
    bOutput = new javax.swing.JButton();
    lInput = new javax.swing.JLabel();
    lOutput = new javax.swing.JLabel();

    bInput.setText("Input file");
    bInput.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bInputActionPerformed(evt);
      }
    });

    bOutput.setText("Output file");
    bOutput.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bOutputActionPerformed(evt);
      }
    });

    lInput.setText("Choose a file");

    lOutput.setText("Choose a file");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(bOutput)
          .addComponent(bInput))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lInput, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
          .addComponent(lOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(bInput)
          .addComponent(lInput))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(bOutput)
          .addComponent(lOutput))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void bInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInputActionPerformed
    
    int r = fileChooser.showOpenDialog(this);
    
    if (r == JFileChooser.APPROVE_OPTION) {
      input = fileChooser.getSelectedFile();
      lInput.setText(input.getName());
    }
  }//GEN-LAST:event_bInputActionPerformed

  private void bOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOutputActionPerformed
    
    int r = fileChooser.showSaveDialog(this);
    
    if (r == JFileChooser.APPROVE_OPTION) {
      output = fileChooser.getSelectedFile();
      lOutput.setText(output.getName());
    }
  }//GEN-LAST:event_bOutputActionPerformed

  File input;
  File output;

  JFileChooser fileChooser;
  
  PopupDialog dialog;
  
  ClassificationPanel cPanel;
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton bInput;
  private javax.swing.JButton bOutput;
  private javax.swing.JLabel lInput;
  private javax.swing.JLabel lOutput;
  // End of variables declaration//GEN-END:variables
}
