/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.midas.classify.gui;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduar Castrillo (eduarc)
 */
public class ValidatorChooser extends javax.swing.JDialog {

  public static final int T_BOOTSTRAP = 0;
  public static final int T_K_FOLD_CROSS = 1;
  public static final int T_RANDOM_SUB_SAMPLING = 2;
  public static final int T_LOOC = 3;
  
  public static final String[] TEST_NAME = {"Bootstrap",
                                            "K-Fold Cross",
                                            "Random Sub-Sampling",
                                            "Leave One Out (LOOC)"};
  /**
   * Creates new form TestSelecter
   */
  public ValidatorChooser() {
    
    setModalityType(ModalityType.APPLICATION_MODAL);
    setResizable(false);
    setUndecorated(true);
    
    initComponents();
    
    listTests.setModel(new javax.swing.AbstractListModel() {
      public int getSize() { return TEST_NAME.length; }
      public Object getElementAt(int i) { return TEST_NAME[i]; }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    listTests = new javax.swing.JList();
    bCancel = new javax.swing.JButton();
    bOk = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    listTests.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    jScrollPane1.setViewportView(listTests);

    bCancel.setText("Cancel");
    bCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bCancelActionPerformed(evt);
      }
    });

    bOk.setText("OK");
    bOk.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bOkActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGroup(layout.createSequentialGroup()
        .addComponent(bOk)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(bCancel)
        .addGap(6, 6, 6))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(bCancel)
          .addComponent(bOk)))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
    
    int i = listTests.getSelectedIndex();
    if (i == -1) {
      JOptionPane.showMessageDialog(this, "Select a test", "Warning", JOptionPane.WARNING_MESSAGE);
    } else {
      selected = i;
      dispose();
    }
  }//GEN-LAST:event_bOkActionPerformed

  private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
    
    selected = -1;
    dispose();
  }//GEN-LAST:event_bCancelActionPerformed

  public int showDialog(Component parent) {
    
    setLocationRelativeTo(parent);
    setVisible(true);
    return selected;
  }
  
  public int getSelectedIndex() {
    return selected;
  }
  
  public String getSelectedName() {
    
    if (selected != -1) {
      return TEST_NAME[selected];
    }
    return null;
  }
  
  int selected = -1;
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton bCancel;
  private javax.swing.JButton bOk;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JList listTests;
  // End of variables declaration//GEN-END:variables
}
