/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.midas.classify.gui.config.model;

import com.midas.classify.gui.ClassificationPanel;
import com.midas.classify.gui.FactoryManager;

/**
 *
 * @author eduarc
 */
public class BaggingConfigPanel extends javax.swing.JPanel {

  ClassificationPanel cPanel;
  
  /**
   * Creates new form BaggingConfigPanel
   * @param cPanel
   */
  public BaggingConfigPanel(ClassificationPanel cPanel) {
    
    this.cPanel = cPanel;
    initComponents();
    
    factoryManager = new FactoryManager(cPanel);
    factoryManager.setBChoose(bModelChoose);
    factoryManager.setBConfig(bModelConfig);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    bModelChoose = new javax.swing.JButton();
    bModelConfig = new javax.swing.JButton();
    lK = new javax.swing.JLabel();
    tfK = new javax.swing.JTextField();

    bModelChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/midas/classify/gui/icons/edit-find.png"))); // NOI18N

    bModelConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/midas/classify/gui/icons/edit.png"))); // NOI18N
    bModelConfig.setText("Configure Base Model");
    bModelConfig.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

    lK.setText("# Classifiers");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(bModelChoose)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(bModelConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lK)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfK, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(6, 6, 6)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(bModelChoose)
          .addComponent(bModelConfig))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lK)
          .addComponent(tfK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 12, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  
  FactoryManager factoryManager;
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  javax.swing.JButton bModelChoose;
  javax.swing.JButton bModelConfig;
  private javax.swing.JLabel lK;
  javax.swing.JTextField tfK;
  // End of variables declaration//GEN-END:variables
}
